# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-10 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180310_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='Article_img/%Y/%m', verbose_name='图片'),
        ),
    ]
