# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 11:29
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180310_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pic',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
